library(mgcv)
library(glue)
library(tidyverse)
library(tidymodels)
library(magrittr)
library(sf)
library(gstat)
library(tweedie)
library(statmod)
library(pracma)
library(fields)
library(units)
library(igraph)
library(ggnetwork)
library(scales)
library(viridis)
library(classInt)
library(patchwork)
library(Rtsne)
library(ggforce)
library(CASdatasets)

sf_use_s2(FALSE)

set.seed(999)

zoom_dims <- dev.size("in")

source("./Code/Belgium_example/1_function_definitions.R")
source("./Code/Belgium_example/2_data_manipulation.R")
source("./Code/Belgium_example/3_graphs.R")
source("./Code/Belgium_example/4_modeling.R")
source("./Code/Belgium_example/5_predictions.R")
source("./Code/Belgium_example/6_final_smoothing.R")
